# Generated by Django 4.1.7 on 2023-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_design', '0002_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
    ]
