# Generated by Django 4.1.7 on 2023-06-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_design', '0003_delete_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Img', models.ImageField(upload_to='pics')),
                ('Desc', models.TextField()),
            ],
        ),
    ]
