# Generated by Django 4.1.7 on 2023-06-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_design', '0004_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='Img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='Name',
            new_name='name',
        ),
    ]
