# Generated by Django 4.1.7 on 2023-06-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_design', '0005_rename_desc_guide_desc_rename_img_guide_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='desc',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='img',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='name',
            new_name='Name',
        ),
    ]
