# Generated by Django 4.1.7 on 2023-06-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_design', '0006_rename_desc_guide_desc_rename_img_guide_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
