# Generated by Django 4.1.7 on 2023-03-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-07-10'),
            preserve_default=False,
        ),
    ]
